name: bugz_utilities
description: Procedures for bots generation and match
version: 1.0.0

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  bugz_common:
    git:
      url: https://github.com/izolenta/bugz-common.git
